### ISSUE TITLE
invoke prompt from voice not working

### ISSUE THREAD

**Issue by ket0x4** [ket0x4/ketard-ai#19]
Logs:
```
Traceback (most recent call last):
  File "/home/ket/ket.ai/.venv/lib/python3.11/site-packages/pyrogram/dispatcher.py", line 355, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/ket/ket.ai/ketard/utils/wrappers.py", line 21, in wrapper
    return await mystic(client, message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ket/ket.ai/ketard/plugins/ddgai.py", line 18, in handle_ddg_command
    prompt = await get_prompt(message=message)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ket/ket.ai/ketard/utils/helper.py", line 31, in get_prompt
    voice_text = await recognizer.convert_and_recognize(voice=voice)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ket/ket.ai/ketard/utils/stt.py", line 16, in convert_and_recognize
    with AudioFile(wav) as source:
  File "/home/ket/ket.ai/.venv/lib/python3.11/site-packages/speech_recognition/__init__.py", line 241, in __enter__
    self.audio_reader = wave.open(self.filename_or_fileobject, "rb")
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/wave.py", line 630, in open
    return Wave_read(f)
           ^^^^^^^^^^^^
  File "/usr/lib/python3.11/wave.py", line 280, in __init__
    f = builtins.open(f, 'rb')
        ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/ket/ket.ai/downloads/voice_2024-06-26_21-09-46_7384875826551980048.ogg.wav'
2024-06-26 21:11:34,876 - ERROR - [Errno 2] No such file or directory: '/home/ket/ket.ai/downloads/voice_2024-06-26_21-09-46_7384876264638644236.ogg.wav'
Traceback (most recent call last):
  File "/home/ket/ket.ai/.venv/lib/python3.11/site-packages/pyrogram/dispatcher.py", line 355, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/ket/ket.ai/ketard/utils/wrappers.py", line 21, in wrapper
    return await mystic(client, message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ket/ket.ai/ketard/plugins/ddgai.py", line 18, in handle_ddg_command
    prompt = await get_prompt(message=message)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ket/ket.ai/ketard/utils/helper.py", line 31, in get_prompt
    voice_text = await recognizer.convert_and_recognize(voice=voice)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ket/ket.ai/ketard/utils/stt.py", line 16, in convert_and_recognize
    with AudioFile(wav) as source:
  File "/home/ket/ket.ai/.venv/lib/python3.11/site-packages/speech_recognition/__init__.py", line 241, in __enter__
    self.audio_reader = wave.open(self.filename_or_fileobject, "rb")
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/wave.py", line 630, in open
    return Wave_read(f)
           ^^^^^^^^^^^^
  File "/usr/lib/python3.11/wave.py", line 280, in __init__
    f = builtins.open(f, 'rb')
        ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/ket/ket.ai/downloads/voice_2024-06-26_21-09-46_7384876264638644236.ogg.wav'
2024-06-26 21:12:46,388 - INFO - Stop signal received (SIGINT). Exiting...

````

**Comment by ket0x4** [comment]
Fixed: dependency issue: install ffmpeg and flac package
